### PR TITLE
Added Hello World script in python

### PR DESCRIPTION
**Pull request by Rishika-7**

### CODE REVIEW

**Comment by caroline-rodrigues** [comment]
Here are 3 quick and painless ways to contribute to this project:

Add your name to the CONTRIBUTORS.md file
Add a profile page to the profiles directory
Create a simple "Hello, World" script in a language of your choice
Before all steps, make a pull request for your work, and wait for it to be merged!

**Comment by Rishika-7** [comment]
I have chosen the third option, is my pull request invalid?

**Comment by caroline-rodrigues** [comment]
You have to do the 3 steps, for your request to be valid

**Comment by Rishika-7** [comment]
Okay I thought that there's an option since it's written one or all three I'll make the necessary changes. Thank you.

**Comment by Rishika-7** [comment]
I have made the changes :)

**Pull request merged**
